tasks:
  - name: install dependencies
    init: |
      pyenv install 3.10.4
      pyenv global 3.10.4
      pip3 install -r requirements.txt
      pip3 install -e .

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
