trainer:
  max_epochs: 100
  limit_train_batches: 1.0
  limit_predict_batches: null
  limit_test_batches: null
  limit_val_batches: null
  accelerator: "auto"
  devices: "auto"
  deterministic: True
  precision: 32
  strategy: single_device
  enable_checkpointing: True
  enable_progress_bar: True
  enable_model_summary: True
  default_root_dir: null
  gradient_clip_val: null
  gradient_clip_algorithm: null
  num_nodes: 1
  num_processes: null
  gpus: null
  auto_select_gpus: null
  tpu_cores: null
  ipus: null
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: False
  accumulate_grad_batches: null
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  val_check_interval: null
  flush_logs_every_n_steps: null
  log_every_n_steps: 50
  sync_batchnorm: False
  weights_save_path: null
  weights_summary: "top"
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  benchmark: null
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: False
  replace_sampler_ddp: True
  detect_anomaly: False
  auto_scale_batch_size: False
  amp_backend: "negative"
  amp_level: null
  move_metrics_to_cpu: False
  multiple_trainloader_mode: "max_size_cycle"
